<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Lucky Draw'=>'抽奖',
  'Break' => '休息',
  'Award Ceremony' => '颁奖',
  'Opening Intro' => '开场简介',
  'Other'=>'其它',
  'Registration'=>'签到',
  'Lunch'=>'午餐',
  'Magic'=>'八板',
  'Funny Event'=>'趣味项目',
);
